name = "nqcc"
version = "1.0.0"
description = "A C compiler implementation in Gleam"
licences = ["MIT"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleamyshell = ">= 2.0.0 and < 3.0.0"
argv = ">= 1.0.0 and < 2.0.0"
glint = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
gleescript = ">= 0.4.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[escript]
main = "nqcc"
